---
title: "Lecture 9: In Class"
author: "FBA Instructors"
format: html
---

## Load Packages and Data

```{r}
library(tidyverse)
library(lubridate)
library(recipes)
library(factoextra)
library(broom)
library(kableExtra)
```

```{r}
purchases <- read_csv("data/cdnow_purchases.csv")

glimpse(purchases)
```

## Build Customer-Level RFM Measures

```{r}
customer_aggregates <-
  purchases |>
  group_by(users_id) |>
  summarise(
    last_purch_date = ,
    frequency       = ,
    monetary        = ,
    .groups = "drop"
  )
```

```{r}
# Construct Recency
YOUR_CODE_HERE
```

## Build Rule-Based RFM Segments

```{r}
rfm_data <-
  customer_aggregates |>
  mutate(
    r_tile = ,
    f_tile = ,
    m_tile = 
  )
```

```{r}
# Reverse Code Recency
YOUR_CODE_HERE
```

```{r}
# Segments based on RULES
rfm_segmented <-
  rfm_data |>
  mutate(
    segment = case_when(
      r_tile == 5 & f_tile == 5 & m_tile == 5 ~ "Champions",
      r_tile %in% 3:5 & f_tile %in% 3:5 & m_tile %in% 2:5 ~ "Potential Loyalist",
      r_tile %in% 2:4 & f_tile %in% 2:4 & m_tile %in% 2:4 ~ "Loyal Customers",
      r_tile %in% 3:4 & f_tile %in% 1:3 & m_tile %in% 3:5 ~ "Promising",
      r_tile %in% 4:5 & f_tile %in% 1:3 & m_tile %in% 1:5 ~ "New Customers",
      r_tile %in% 1:2 & f_tile %in% 3:4 & m_tile %in% 4:5 ~ "Can't Lose Them",
      r_tile %in% 1:2 & f_tile %in% 2:5 & m_tile %in% 4:5 ~ "At Risk",
      r_tile %in% 1:3 & f_tile %in% 3:5 & m_tile %in% 3:5 ~ "Need Attention",
      r_tile %in% 2:3 & f_tile %in% 1:3 & m_tile %in% 1:4 ~ "About To Sleep",
      r_tile == 1 & f_tile %in% 1:5 & m_tile %in% 1:5 ~ "Lost",
      .default = "Unclassified"
    )
  )
```

```{r}
# Summarise Segments
rfm_segmented |>
  group_by(segment) |>
  summarise(
    avg_recency   = mean(recency),
    avg_frequency = mean(frequency),
    avg_monetary  = mean(monetary),
    n_customers   = n(),
    .groups = "drop"
  ) |>
  arrange(desc(n_customers)) |>
  kable(digits = 2)
```

## Build Data-Driven Segments with K-Means

```{r}
# Inspect R F and M measures in data
rfm_data |>
  summarise(
    min_recency   = min(recency),
    max_recency   = max(recency),
    min_frequency = min(frequency),
    max_frequency = max(frequency),
    min_monetary  = min(monetary),
    max_monetary  = max(monetary)
  ) |>
  pivot_longer(
    everything(),
    names_to = c("stat", "variable"),
    names_sep = "_"
  ) |>
  pivot_wider(
    names_from = stat,
    values_from = value
  )
```

```{r}
# Rescale data
YOUR_CODE
```

```{r}
# look at normalized vars
rfm_scaled |>
  summarise(
    across(everything(), list(mean = mean, sd = sd))
  ) |>
  pivot_longer(
    cols = everything(),
    names_to = c("variable", ".value"),
    names_sep = "_"
  ) |>
  kable(digits = 2)
```

```{r}
# Do K-means
YOUR_CODE
```

```{r}
fviz_cluster(
  YOUR_CODE,
  geom = "point",
  ggtheme = theme_minimal()
)
```

```{r}
# Add clusters back to data
YOUR_CODE
```

```{r}
# What patterns in each cluster?
YOUR_CODE
```

## If Time: How Many Clusters?

```{r}
set.seed(42)
rfm_scale_sample <-
  rfm_scaled |>
  sample_n(1000)
```

```{r}
fviz_nbclust(
  rfm_scale_sample,
  kmeans,
  method = "wss",
  k.max = 15,
  nstart = 5
)
```


